// <auto-generated />
using System;
using ECommerce.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerce.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210413035831_DeleteUnitStock")]
    partial class DeleteUnitStock
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECommerce.Backend.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Steam"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Epic"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Microsoft"
                        });
                });

            modelBuilder.Entity("ECommerce.Backend.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Switch",
                            Description = "The Nintendo Switch (known as the NX in development) is a eighth generation home video game console released by Nintendo, and its seventh major home game console as the successor to the Wii U."
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "PC",
                            Description = "Stands for 'Personal computer'. PCs are what most of us use on a daily basis for work or personal use. A typical PC includes a system unit, monitor, keyboard, and mouse."
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "PlayStation",
                            Description = "PS is a video game brand that consists of five home video game consoles, as well as a media center, an online service, a line of controllers, two handhelds and a phone, as well as multiple magazines."
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Xbox",
                            Description = "The brand consists of five video game consoles, as well as applications (games), streaming services, an online service by the name of Xbox Live, and the development arm by the name of Xbox Game Studios."
                        });
                });

            modelBuilder.Entity("ECommerce.Backend.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 935, DateTimeKind.Local).AddTicks(8637),
                            Description = "Join the Phantom Thieves and strike back against the corruption overtaking cities across Japan. A summer vacation with close friends takes a sudden turn as a distorted reality emerges; reveal the truth and redeem the hearts of those imprisoned at the center of the crisis! Jump into the stylish world of Persona in an all-new story Dynamically control your team during explosive action combat Battle across Japan in an epic road trip Key Features Include: /nExperience the world of Persona 5 Strikers on PC in Full HD, supports up to 4K /nSteam Achievements and Trading Cards /nChoose between Japanese and English VO /nFull keyboard and mouse adaptation",
                            Images = "persona-5-scramble-strikers-switch.jpg",
                            Price = 59.99m,
                            ProductName = "Persona 5 - Scramble Striker",
                            UpdatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(3198)
                        },
                        new
                        {
                            ProductId = 2,
                            BrandId = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5389),
                            Description = "Florence is a heartfelt experience that lasts around 30 minutes. It's short, but deeply meaningful. At 25, Florence Yeoh feels a little stuck. Her life is an endless routine of work, sleep, and spending too much time on social media. Then one day, she meets a cello player named Krish who changes everything about how she sees the world. Experience every beat of Florence and Krish’s relationship through a series of bespoke gameplay vignettes – from flirting to fighting, from helping each other grow to growing apart. Drawing inspiration from ‘slice of life’ graphic novels and webcomics, Florence is intimate, raw and personal. Original soundtrack included.",
                            Images = "florence-switch-cover.jpg",
                            Price = 4.99m,
                            ProductName = "Florence",
                            UpdatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5496)
                        },
                        new
                        {
                            ProductId = 3,
                            BrandId = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5520),
                            Description = "The game follows Jill Valentine as she attempts to escape a zombie outbreak while hunted by an intelligent bioweapon known as Nemesis-T Type. The game comes bundled with Resident Evil: Resistance, an online asymmetrical game. ",
                            Images = "resident-evil-3-switch-cover.jpg",
                            Price = 59.99m,
                            ProductName = "Resident Evil 3 Remake",
                            UpdatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5523)
                        },
                        new
                        {
                            ProductId = 4,
                            BrandId = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5528),
                            Description = "Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Santos and Blaine County in resolutions of up to 4k and beyond, as well as the chance to experience the game running at 60 frames per second. ",
                            Images = "grand-theft-auto-v-cover.jpg",
                            Price = 34.99m,
                            ProductName = "Grand Theft Auto V",
                            UpdatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5531)
                        },
                        new
                        {
                            ProductId = 5,
                            BrandId = 3,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5535),
                            Description = "Embark on the craziest journey of your life in It Takes Two. Invite a friend to join for free with Friend’s Pass and work together across a huge variety of gleefully disruptive gameplay challenges. ",
                            Images = "it-takes-two-english-only-cover.jpg",
                            Price = 34.99m,
                            ProductName = "It Takes Two",
                            UpdatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5538)
                        },
                        new
                        {
                            ProductId = 6,
                            BrandId = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5542),
                            Description = "Ushering in a new era for the METAL GEAR franchise with cutting-edge technology powered by the Fox Engine, METAL GEAR SOLID V: The Phantom Pain, will provide players a first-rate gaming experience as they are offered tactical freedom to carry out open-world missions. ",
                            Images = "metal-gear-solid-v-the-phantom-pain.jpg",
                            Price = 29.99m,
                            ProductName = "Metal Gear Solid V - The Phantom Pain",
                            UpdatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5545)
                        },
                        new
                        {
                            ProductId = 7,
                            BrandId = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5549),
                            Description = "Outriders’ brutal and bloody combat combines frenetic gunplay, violent powers and deep RPG systems to create a true genre hybrid. ",
                            Images = "outriders-cover.jpg",
                            Price = 59.99m,
                            ProductName = "Outriders",
                            UpdatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5551)
                        },
                        new
                        {
                            ProductId = 8,
                            BrandId = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5555),
                            Description = "Experience survival horror like never before in the 8th major installment in the Resident Evil franchise - Resident Evil Village. With detailed graphics, intense first-person action and masterful storytelling, the terror has never felt more realistic. ",
                            Images = "resident-evil-village-deluxe-edition-cover.jpg",
                            Price = 59.99m,
                            ProductName = "Resident Evil Village",
                            UpdatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5557)
                        },
                        new
                        {
                            ProductId = 9,
                            BrandId = 3,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5563),
                            Description = "As war rages on throughout the Northern Realms, you take on the greatest contract of your life — tracking down the Child of Prophecy, a living weapon that can alter the shape of the world.",
                            Images = "the-witcher-3.jpg",
                            Price = 19.99m,
                            ProductName = "The Witcher 3",
                            UpdatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5565)
                        },
                        new
                        {
                            ProductId = 10,
                            BrandId = 4,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5569),
                            Description = "The story of this first, standalone game in the FINAL FANTASY VII REMAKE project covers up to the party’s escape from Midgar, and goes deeper into the events occurring in Midgar than the original FINAL FANTASY VII.",
                            Images = "final-fantasy-vii-remake-ps4-cover.jpg",
                            Price = 59.99m,
                            ProductName = "Final Fantasy VII Remake",
                            UpdatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5572)
                        },
                        new
                        {
                            ProductId = 11,
                            BrandId = 4,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5576),
                            Description = "As war rages on throughout the Northern Realms, you take on the greatest contract of your life — tracking down the Child of Prophecy, a living weapon that can alter the shape of the world. ",
                            Images = "god-of-war-4.jpg",
                            Price = 49.99m,
                            ProductName = "God Of War 4",
                            UpdatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5578)
                        },
                        new
                        {
                            ProductId = 12,
                            BrandId = 4,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5582),
                            Description = "Battle hordes of yokai in this masocore Action RPG. Create your protagonist and embark on an adventure through a myriad of locales across Japan during the Sengoku period. Utilize the new Yokai Shift ability to defeat even the most ferocious yokai and be prepared to brave through Dark Realms created by your...",
                            Images = "nioh-2-the-complete-edition-ps4-cover.jpg",
                            Price = 49.99m,
                            ProductName = "Nioh 2",
                            UpdatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5585)
                        },
                        new
                        {
                            ProductId = 13,
                            BrandId = 4,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5589),
                            Description = "Release in 2022",
                            Images = "dragon-quest-iii-remake-ps5.jpg",
                            Price = 49.99m,
                            ProductName = "Dragon Quest III Remake",
                            UpdatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5591)
                        },
                        new
                        {
                            ProductId = 14,
                            BrandId = 5,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5595),
                            Description = "Release in 2022",
                            Images = "assassin-2019s-creed-valhalla.jpg",
                            Price = 49.99m,
                            ProductName = "Assassin Creed Valhalla",
                            UpdatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5597)
                        },
                        new
                        {
                            ProductId = 15,
                            BrandId = 5,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5602),
                            Description = "As war rages on throughout the Northern Realms, you take on the greatest contract of your life — tracking down the Child of Prophecy, a living weapon that can alter the shape of the world. ",
                            Images = "the-witcher-3-xbox.jpg",
                            Price = 19.99m,
                            ProductName = "The Witcher 3",
                            UpdatedDate = new DateTime(2021, 4, 13, 10, 58, 29, 937, DateTimeKind.Local).AddTicks(5604)
                        });
                });

            modelBuilder.Entity("ECommerce.Backend.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("RatingBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RatingTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("RatingValue")
                        .HasColumnType("real");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RatingId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("ECommerce.Backend.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ECommerce.Backend.Models.Product", b =>
                {
                    b.HasOne("ECommerce.Backend.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Backend.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.Backend.Models.Rating", b =>
                {
                    b.HasOne("ECommerce.Backend.Models.Product", "Product")
                        .WithMany("Ratings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Backend.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ECommerce.Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ECommerce.Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ECommerce.Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Backend.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerce.Backend.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerce.Backend.Models.Product", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("ECommerce.Backend.Models.User", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
